### ISSUE TITLE
How to go new Level?

### ISSUE THREAD

**Issue by SirazumMuniraTisha** [SirazumMuniraTisha/CSC4263-ART4240#3]

**Comment by YenJungChen** [comment]
I think Yalda's idea is perfect. We can make a narrow tunnel for the capsule, and after the capsule clean all the obstacle, it can go to the next level.
In our previous meet, we agreed that make all the things in one scene will be easier. But I have a little research for making a new scene, so please let me try. If it works, we can use a new scene. (It will be more clear for object-oriented programming.) However, if anyone has better idea, please let us know.
